//Components
import Sidebar from "@/components/TopBar/TopBar";

//Store
import { AppProvider } from "@/store/provider";

//Styles
import "@/styles/global.scss";

//Utils
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <Sidebar />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
